# Generated by Django 5.2.3 on 2025-06-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_num',
            field=models.CharField(default='9846357621', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=20),
        ),
    ]
